[[redirects]]
  force = true
  from = "/fonts/CentraNo2-Light.woff"
  status = 200
  to = "https://www.fortomorrow.eu/assets/common/font/CentraNo2-Light.woff"

[[redirects]]
  force = true
  from = "/fonts/CentraNo2-Light.woff2"
  status = 200
  to = "https://www.fortomorrow.eu/assets/common/font/CentraNo2-Light.woff2"

